FROM python:3.9.5
# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# add requirements
COPY ./requirements.txt requirements.txt
# install requirements
RUN pip install -r requirements.txt
# add app
COPY . /services/users/project
# run server
CMD python manage.py run -h 0.0.0.0